[package]
name = "user"
version = "0.1.0"
authors = ["Serious-senpai"]
edition = "2024"
description = "A super simple WDM driver"

[dependencies]
clap = { version = "4.5.49", features = ["cargo", "derive"] }
