name: Build

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    name: Test build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90"
          cache: false
          rustflags: ""

      - name: Setup repository
        shell: cmd
        run: |
          extern\wdksetup.exe /features + /log "%cd%\wdksetup.log" /quiet
          cargo install --locked cargo-make --no-default-features --features tls-native

      - name: Build kernel driver
        shell: cmd
        working-directory: kernel
        run: |
          set LIBCLANG_PATH=%cd%\..\extern\clang-llvm-21.1.3
          cargo make default --release

      - name: Build user application
        shell: cmd
        working-directory: user
        run: |
          cargo build --release

      - name: Upload build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            wdksetup.log
            kernel/target/release/logging_driver_package
            user/target/release/user.exe
